[build]
  command = "npm run build:netlify"
  publish = "netlify-dist"

[build.environment]
  NODE_VERSION = "22.13.0"

[dev]
  command = "npm run dev"
  targetPort = 3000
  port = 8888
  framework = "#custom"
